version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: essaycoach-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # You can override these in a local .env file (see .env.example)
      POSTGRES_USER: ${POSTGRES_USER:-essayadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-essaycoach}
    volumes:
      # Persistent data volume
      - ./docker/db/data:/var/lib/postgresql/data
      # Initialisation scripts (executed on first run only)
      - ./docker/db/init:/docker-entrypoint-initdb.d 